services:
  hdfs-master:
    container_name: hdfs-master
    build:
      context: .
      dockerfile: ./master/Dockerfile
    networks: 
      - sharednet
    ports:
      - 9870:9870
      - 54310:54310
    volumes:
      - master-volume:/hadoop/dfs/data
  
  hdfs-worker:
    container_name: hdfs-worker
    image: matnar/hadoop:3.3.2
    networks: 
      - sharednet

networks:
  sharednet:
    external: true
    name: prj1

volumes:
  master-volume:
    external: true
